USE master
DROP DATABASE LIVRARIA

CREATE DATABASE LIVRARIA
USE LIVRARIA

CREATE TABLE LIVRO(
CODIGO INT NOT NULL IDENTITY(100001,100),
NOME VARCHAR(200) NOT NULL,
LINGUA VARCHAR(10) NOT NULL DEFAULT('PT-BR'),
ANO INT NOT NULL CHECK(ANO < 1990)
)
GO
CREATE TABLE AUTOR(
ID_AUTOR INT NOT NULL IDENTITY (2351,1),
NOME VARCHAR(100) NOT NULL UNIQUE,
DATA_NASC DATE NOT NULL,
PAIS_NASC VARCHAR(50) NOT NULL,
BIBLIOGRAFIA VARCHAR(255) NOT NULL,
CONSTRAINT chk_PAISNASC CHECK((UPPER(PAIS_NASC) = 'brasil' OR UPPER(PAIS_NASC) = 'estados unidos' OR UPPER(PAIS_NASC) = 'inglaterra' OR UPPER(PAIS_NASC) = 'alemanha'))
)
GO
CREATE TABLE EDITORA(
ID_EDITORA INT NOT NULL IDENTITY(491,1),
NOME VARCHAR(70) NOT NULL UNIQUE,
TELEFONE VARCHAR (11) NOT NULL  CHECK(TELEFONE = 10) ,
LOUGRADOURO_ENDERECO VARCHAR(200) NOT NULL,
NUMERO_ENDERECO INT NOT NULL CHECK(NUMERO_ENDERECO < 0) ,
CEP_ENDERECO CHAR(8) NOT NULL  CHECK(CEP_ENDERECO ='8'),
COMPLEMENTO_ENDERECO VARCHAR(255) NOT NULL
)
GO
CREATE TABLE EDICAO(
ISBN CHAR (13) NOT NULL CHECK(LEN(ISBN) = 13),
PRECO DECIMAL (4,2) NOT NULL CHECK(PRECO < 0),
ANO INT NOT NULL CHECK(ANO < 1993),
NUMERO_PAGINAS INT NOT NULL CHECK(NUMERO_PAGINAS < 15),
QTDESTOQUE INT NOT NULL
)
GO
 CREATE TABLE LIVRO_AUTOR(
 COD_LIVRO INT NOT NULL,
 AUTOR_ID INT NOT NULL
 FOREIGN KEY (COD_LIVRO) REFERENCES LIVRO (CODIGO),
 FOREIGN KEY (AUTOR_ID)  REFERENCES AUTOR(ID_AUTOR)
 )
 GO
 CREATE TABLE EDITORA_EDICAO_LIVRO(
 EDITORA_ID INT NOT NULL,
 EDICAOISBN CHAR(13) NOT NULL,
 LIVRO_CODIGO INT NOT NULL
 FOREIGN KEY(EDITORA_ID) REFERENCES EDITORA(ID_EDITORA),
 FOREIGN KEY (EDICAOISBN) REFERENCES EDICAO(ISBN),
 FOREIGN KEY (LIVRO_CODIGO) REFERENCES LIVRO(CODIGO)
 )
EXEC sp_help LIVRO